site_name: BAR Infrastructure
site_url: https://beyond-all-reason.github.io/infrastructure
repo_url: https://github.com/beyond-all-reason/infrastructure
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
