classes: {
  # Unfortunately, custom colors don't work well with
  # dark mode yet :(.
  # Waiting for https://github.com/terrastruct/d2/issues/831/
  gcp: {style.fill: "#d0ecff"}
  cloudflare: {style.fill: "#fff3d0"}
  github: {style.fill: "#ebffe3"}
  vm: {style.fill: "#ffe3f1"}
}
