name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for git-revision-date-localized-plugin plugin
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install D2
        run: curl -fsSL https://d2lang.com/install.sh | sh -s -- --tala
      - name: Build and push docs
        run: mkdocs gh-deploy --force
        env:
          TSTRUCT_TOKEN: ${{ secrets.TSTRUCT_TOKEN }}
